[package]
name = "juan-lang"
version = "0.0.0"
description = "A fast bytecode-interpreted scripting language that provides logically safe features."
edition.workspace = true
license.workspace = true
readme.workspace = true
repository.workspace = true
authors.workspace = true
rust-version.workspace = true
keywords = ["cli", "language"]
categories = ["compilers", "command-line-utilities"]

[dependencies]
